### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by banerjeesoumya15**
#### Issue Number #3 
ISSUE #

#### Describe the changes you've made
Updated README.md with link to CONTRIBUTING.md

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

#### Test plan (OPTIONAL)
A good test plan should give instructions that someone else can easily follow.
How someone can test your code?

#### Checklist

- [ ] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **[CONTRIBUTING](https://github.com/GameofSource-GFG/Web-Development/blob/main/CONTRIBUTING.md)** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] The title of my pull request is a short description of the requested changes.
- [ ] Participating in SWOC2021.
- [ ] Participating in DWOC.

### CODE REVIEW

**Comment by banerjeesoumya15** [comment]
Hi @akrish4 
Can you please review this Pull Request?

**Review by akrish4 — APPROVED** [review]
Thankyou for taking time in making a PR.
I recommend you to contribute in the main content instead of improving README.
Thanks

**Comment by banerjeesoumya15** [comment]
Your repository doesn't give a clear indication what the repository is about. If you can explain in README.md about the purpose of the repository, it would be great for other developers to contribute.

Thanks for approving my PR 😃

**Comment by akrish4** [comment]
For understanding it , you should first go through it instead of just
opening a docs PR.

Thanks

**Pull request merged**
